# Generated by Django 3.0.3 on 2020-02-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publishedDate', models.DateField()),
                ('isbn_10', models.IntegerField()),
                ('isbn_13', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('cover', models.URLField()),
                ('language', models.CharField(max_length=64)),
                ('authors', models.ManyToManyField(to='google_books.Author')),
            ],
        ),
    ]
