# Generated by Django 3.0.3 on 2020-02-10 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('google_books', '0002_auto_20200210_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn_10',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn_13',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishedDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_books.Language'),
        ),
    ]
