# Generated by Django 3.0.3 on 2020-02-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_books', '0003_auto_20200210_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publishedDate',
        ),
        migrations.AddField(
            model_name='book',
            name='publishedDay',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publishedMonth',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publishedYear',
            field=models.IntegerField(null=True),
        ),
    ]
