# Generated by Django 3.0.3 on 2020-02-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_books', '0005_auto_20200210_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_10',
            field=models.BigIntegerField(null=True),
        ),
    ]
